---
classes:
  - profile::cephfs
  - packages::manage
  - podman
  - profile::users::poolaccounts

profile::monitored::use_prometheus: false

profile::users::shell: '/sbin/nologin'

profile::cephfs::keys:
  - condor
  - dice-user

profile::cephfs::mounts:
  '/condor':
    device: condor@.dicefs=/condor
  '/dice':
    device: dice-user@.dicefs=/dice
  '/xrootd':
    device: dice-user@.dicefs=/xrootd

