---
classes:
  - packages::manage
  - podman
  - profile::apptainer
  - profile::cvmfs
  - profile::cephfs
  - profile::heposlibs
  - profile::htcondor
  - profile::nfs_mounts
  - profile::users::poolaccounts

profile::htcondor::role: "execute"

podman::enable_api_socket: true
profile::monitored::use_prometheus: false

profile::users::shell: '/sbin/nologin'

cvmfs::cvmfs_cache_base: '/var/cache/cvmfs'

profile::cephfs::keys:
  - condor
  - dice-user

profile::cephfs::mounts:
  '/condor':
    device: condor@.dicefs=/condor
  '/dice':
    device: dice-user@.dicefs=/dice
  '/xrootd':
    device: dice-user@.dicefs=/xrootd

profile::nfs_mounts::mounts:
  '/shared/scratch':
    path: /exports/scratch
    read_only: false
    group: users
  '/users':
    path: /exports/users
    read_only: true
  '/software':
    path: /exports/software
    read_only: true
    group: users
  '/opt/astro':
    server: echidna.star.bris.ac.uk
    path: /data/echidna1
    read_only: true
    group: dice-astro

firewalld::ports:
  "Open standard condor ports":
    ensure: present
    zone: public
    port: 9618
    protocol: 'tcp'
