classes:
  - profile::firewalld
  - profile::cephfs
  - profile::grid_cert
  - 'profile::backed_up'

site::node_info:
  users: poolaccounts

profile::users::shell: '/sbin/nologin'

firewalld::ports:
  "Open port 9618 for condor":
    ensure: present
    zone: public
    port: 9618
    protocol: 'tcp'
  "Open port 9619 for condor-ce":
    ensure: present
    zone: public
    port: 9619
    protocol: 'tcp'

firewalld::services:
  "Allow access to HTTP service on port 80 for CEView (internal only)":
    service: http
    zone: public
    ensure: present

profile::cephfs::keys:
  - dice-user

profile::cephfs::mounts:
  '/condor':
    device: dice-user@.dicefs=/condor
  '/dice':
    device: dice-user@.dicefs=/dice
  '/xrootd':
    device: dice-user@.dicefs=/xrootd
